# image will be published to ghcr.io/<user>/<name>
name: dan-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-silverblue-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-41/atim-starship-fedora-41.repo
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # Terminal Prompt
      - starship
      # Terminal
      - tmux
      - fish
      # modern cli tools
      - neovim
      - duf
      - bat  
      - git-delta
      - gitui
      - procs
      - fzf
      - lsd
      - eza
      - fd-find
      - httpie
      - procs
      - tldr
      # VM tools
      - virt-manager
      # SELinux tools
      - setroubleshoot-server
      - policycoreutils-python-utils
      # # Other apps
      - texstudio
      # Extra tools
      - distrobox
      - system76-keyboard-configurator
 
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - org.videolan.VLC
        - io.missioncenter.MissionCenter
        - com.discordapp.Discord
        - com.bitwarden.desktop
        - com.valvesoftware.Steam
        - com.github.tchx84.Flatseal
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.BackgroundRemoval
        - me.proton.Mail
      remove:
      # - org.gnome.eog
  - type: akmods
    install:
      #- v4l2loopback
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
